### ISSUE TITLE
Move update popup to chat message

### ISSUE THREAD

**Issue by poxun1** [stpain/guildbook#39]
We were trying to get our guild to adopt this addon however several players opted out/uninstalled due to being annoyed by the update popup 'popping' into the middle of their screen while they were in the middle of doing something else.

It is unnecessary to give a copyable url to update from as most players use CurseForge or other auto-updaters anyway.

Please move the reminder to update to a chat message.  I feel this would help with wider adoption.

**Comment by Bonkeybee** [comment]
Please please please remove the popup. I had just got most of my guild to adopt this and now they are all complaining or uninstalling the addon because of the update popup.

I know it's important for people to update because you've been doing an amazing job adding/fixing features. But this one needs to go.

**Comment by stpain** [comment]
Its been removed and i added an option to disable the print messages!
